apiVersion: v1
kind: Service
metadata:
  name: tours-booking-service
  namespace: tours-booking
spec:
  selector:
    app: tours-booking
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
