name: Deploy to Kubernetes

on:
  #   push:
  #     branches: [main]
  #   pull_request:
  #     branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted
    # runs-on: my-k8s-runner # <--- Runs on your self-hosted runner

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Environment Variables
        run: |
          REPO_OWNER=$(echo '${{ github.repository_owner }}' | tr '[:upper:]' '[:lower:]')
          REPO_NAME=$(echo '${{ github.event.repository.name }}' | tr '[:upper:]' '[:lower:]')
          echo "REPO_OWNER=$REPO_OWNER" >> $GITHUB_ENV
          echo "REPO_NAME=$REPO_NAME" >> $GITHUB_ENV
          echo "SOURCE_REGISTRY=ghcr.io" >> $GITHUB_ENV
          echo "SOURCE_IMAGE=ghcr.io/$REPO_OWNER/$REPO_NAME" >> $GITHUB_ENV
          echo "SOURCE_IMAGE_TAG=latest" >> $GITHUB_ENV

      - name: Debug Environment Variables
        run: |
          echo "SOURCE_REGISTRY=${SOURCE_REGISTRY}"
          echo "REPO_OWNER=${REPO_OWNER}"
          echo "REPO_NAME=${REPO_NAME}"
          echo "SOURCE_IMAGE=${SOURCE_IMAGE}"
          echo "SOURCE_IMAGE_TAG=${SOURCE_IMAGE_TAG}"

      - name: Authenticate with GHCR (If Private)
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin

      - name: Pull Latest Image on the Self-Hosted Runner
        run: |
          docker pull ${SOURCE_IMAGE}:latest

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f k8s/deployment.yml
          kubectl apply -f k8s/service.yml
          kubectl set image deployment/tours-booking tours-booking=${SOURCE_IMAGE}:latest -n tours-booking
          kubectl rollout status deployment/tours-booking -n tours-booking
