name: Build & Publish to GitHub Package Registry (GHCR)

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "17"

      - name: Build JAR with Maven
        run: mvn clean package

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u "${{ secrets.GHCR_USERNAME }}" --password-stdin

      - name: Build Docker Image
        run: |
          docker build -t ghcr.io/${{ secrets.GHCR_USERNAME }}/tours-booking:latest .
          docker tag ghcr.io/${{ secrets.GHCR_USERNAME }}/tours-booking:latest ghcr.io/${{ secrets.GHCR_USERNAME }}/tours-booking:0.1.0

      - name: Push Docker Image to GitHub Package Registry
        run: |
          docker push ghcr.io/${{ secrets.GHCR_USERNAME }}/tours-booking:latest
          docker push ghcr.io/${{ secrets.GHCR_USERNAME }}/tours-booking:0.1.0
