name: JFrog Integration

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JFrog CLI
        uses: jfrog/setup-jfrog-cli@v4
        with:
          version: latest

      - name: Configure JFrog CLI
        run: |
          jfrog config add my-jfrog-server \
            --url=${{ secrets.JFROG_URL }} \
            --user=${{ secrets.JFROG_USERNAME }} \
            --password=${{ secrets.JFROG_TOKEN }} \
            --interactive=false
          
      - name: Verify JFrog Connection
        run: |
          jfrog rt ping

      - name: Upload Artifact to JFrog
        run: |
          jfrog rt u "build/*.jar" my-repo/
