name: Deploy NGINX to Kubernetes

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set KUBECONFIG and Ensure sudo Access
        run: |
          echo "Setting KUBECONFIG..."
          export KUBECONFIG=/etc/kubernetes/admin.conf
          echo "KUBECONFIG=/etc/kubernetes/admin.conf" >> $GITHUB_ENV

          echo "Ensuring sudo access for kubectl..."
          sudo ls > /dev/null  # Ensures GitHub Actions can use sudo without password prompt
          sudo chown $USER:$USER /etc/kubernetes/admin.conf
          sudo chmod 644 /etc/kubernetes/admin.conf

      - name: Debug Kubernetes Connection
        run: |
          echo "Checking Kubernetes Connection..."
          sudo kubectl cluster-info || { echo "❌ K8s cluster not reachable!"; exit 1; }
          sudo kubectl get nodes || { echo "❌ Failed to get nodes!"; exit 1; }

      - name: Deploy NGINX to Kubernetes
        run: |
          echo "Creating namespace..."
          sudo kubectl create namespace nginx-test --dry-run=client -o yaml | sudo kubectl apply --validate=false -f -

          echo "Deploying NGINX..."
          sudo kubectl run nginx --image=nginx:latest --port=80 --namespace=nginx-test --restart=Always

          echo "Exposing NGINX service..."
          sudo kubectl expose pod nginx --type=LoadBalancer --port=80 --target-port=80 --namespace=nginx-test

          echo "Waiting for rollout..."
          sudo kubectl rollout status deployment nginx -n nginx-test || true
