name: Deploy NGINX to Kubernetes

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Debug Kubernetes Access
        run: |
          echo "Checking Kubernetes Connection..."
          kubectl cluster-info || { echo "❌ K8s cluster not reachable!"; exit 1; }
          kubectl get nodes || { echo "❌ Failed to get nodes!"; exit 1; }

      - name: Deploy NGINX to Kubernetes
        run: |
          # Ensure namespace exists
          kubectl create namespace nginx-test --dry-run=client -o yaml | kubectl apply --validate=false -f -

          # Deploy NGINX without a YAML file
          kubectl run nginx --image=nginx:latest --port=80 --namespace=nginx-test --restart=Always

          # Expose NGINX as a service
          kubectl expose pod nginx --type=LoadBalancer --port=80 --target-port=80 --namespace=nginx-test

          # Wait for rollout
          kubectl rollout status deployment nginx -n nginx-test || true
