name: Deploy NGINX Pod to Kubernetes

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Verify Cluster Access
        run: |
          kubectl config view  
          kubectl cluster-info 
          kubectl get nodes

      - name: Delete Existing NGINX Pod (if exists)
        run: |
          kubectl delete pod nginx --ignore-not-found=true

      - name: Deploy NGINX Pod
        run: |
          kubectl run nginx --image=nginx --port=80 --restart=Never

      - name: Expose NGINX Pod as a Service
        run: |
          kubectl expose pod nginx --port=80 --type=NodePort --overwrite=true

      - name: Verify Deployment
        run: |
          kubectl get pod nginx
          kubectl get svc nginx
