name: Deploy NGINX to Kubernetes

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Configure KUBECONFIG
        run: |
          # Use a dedicated kubeconfig file (not admin.conf)
          mkdir -p ~/.kube
          echo "$KUBECONFIG_DATA" > ~/.kube/config  # Securely pass kubeconfig via GitHub Secrets
          chmod 600 ~/.kube/config

      - name: Deploy NGINX via Manifest
        run: |
          # Create namespace
          kubectl create namespace nginx-test --dry-run=client -o yaml | kubectl apply -f -

          # Deploy NGINX via Deployment/Service YAML
          kubectl apply -f - <<EOF
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: nginx
            namespace: nginx-test
          spec:
            replicas: 1
            selector:
              matchLabels:
                app: nginx
            template:
              metadata:
                labels:
                  app: nginx
              spec:
                containers:
                - name: nginx
                  image: nginx:latest
                  ports:
                  - containerPort: 80
          ---
          apiVersion: v1
          kind: Service
          metadata:
            name: nginx
            namespace: nginx-test
          spec:
            type: NodePort  # Use NodePort for local clusters
            selector:
              app: nginx
            ports:
              - port: 80
                targetPort: 80
          EOF

      - name: Verify Deployment
        run: |
          kubectl rollout status deployment/nginx -n nginx-test
          kubectl get svc/nginx -n nginx-test  # Check assigned NodePort
