name: Test GitHub Environment Variables

on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - ".github/**"
      - "**.md"

jobs:
  test-env-vars:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set and Append Environment Variables
        run: |
          echo "TEST_VERSION=1.2.3" >> $GITHUB_ENV
          echo "TEST_MINOR=18" >> $GITHUB_ENV

      - name: Verify Environment Variables
        run: |
          echo "Extracted TEST_VERSION: $TEST_VERSION"
          echo "Extracted TEST_MINOR: $TEST_MINOR"

      - name: Set Dynamic Artifactory Paths
        run: |
          echo "Setting ARTIFACTORY_REPO dynamically..."
          echo "REPO_PATH=/var/temp/${TEST_VERSION}-${TEST_MINOR}.amd/" >> $GITHUB_ENV

      - name: Verify Final Artifactory Path
        run: |
          echo "Final Artifactory Path: $REPO_PATH"
