name: Test GitHub Environment Variables

on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - ".github/**"
      - "**.md"

jobs:
  test-env-vars:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set and Append Environment Variables
        run: |
          TEMP1=1.2.3
          TEMP2=18
          echo "TEST_VERSION=${TEMP1}" >> $GITHUB_ENV
          echo "TEST_MINOR=$TEMP2" >> $GITHUB_ENV

      - name: Verify Environment Variables
        run: |
          echo "Extracted TEST_VERSION: $TEST_VERSION"
          echo "Extracted TEST_MINOR: $TEST_MINOR"

      - name: Set Dynamic Artifactory Paths
        run: |
          echo "Set ARTIFACTORY_REPO dynamically..."
          REPO_PATH="/var/tmp/$TEST_VERSION-$TEST_MINOR.iso/"
          echo "REPO_PATH=${REPO_PATH}" >> $GITHUB_ENV

      - name: Verify Environment Variables
        run: |
          echo "Final Artifactory Path: ${REPO_PATH}"
